num1 = int(input('Enter num1 as decimal: '))
num2 = int(input('Enter num2 as decimal: '))

print('Sum ', num1 + num2)
print('Sub ', num1 - num2)
print('Multiplication ', num1 * num2)
print('Division ', num1 / num2)
print('Floor Division (Display only digit not float number)) ', num1 // num2)
print('Exponent  ', num1 ** num2)
print('Moduls or (reminder) ', num1 % num2)
