x = None 
y = 2 

print(x)
print(y)

a = bool(0)
print('a is ', a)
b = bool(1)
print('b is ', b)
c = bool(12)
print('c is ', c)
d = bool(-1)
print('d is ', d)
e = bool(0.0)
print('e is ', e)
f = bool(-3.4)
print('f is ', f)
g = bool(0.201)
print('g is ', g)
h = bool(-0.201)
print('h is ', h)
i = bool([])
print('i is ', i)
j = bool([3, -1, 8])
print('j is ', j)
k = bool('')
print('k is ', k)
l = bool('Hello')
print('l is ', l)
m = bool('False')
print('m is ', m)
n = bool('True')
print('n is ', n)
o = bool({})
print('o os ', o)